export interface AreaData {
  slug: string;
  name: string;
  county: string;
  intro: string;
  localDesc: string;
}

export const areas: AreaData[] = [
  { slug: "naas", name: "Naas", county: "Kildare", intro: "As the county town of Kildare, Naas is a thriving business hub with a growing demand for professional digital marketing services. Our team brings Dublin-level expertise to local Naas businesses, helping them compete effectively online.", localDesc: "Whether you're based in Millennium Park, on Main Street, or anywhere in the Naas area, we understand the local market dynamics and consumer behaviour that drive success in County Kildare." },
  { slug: "navan", name: "Navan", county: "Meath", intro: "Navan is one of Meath's fastest-growing towns, and local businesses need strong digital marketing to stand out. We provide comprehensive marketing services to Navan businesses, from SEO and web design to social media management.", localDesc: "From the town centre to the surrounding Navan business parks, we help Meath-based businesses build a powerful online presence that attracts local customers and drives growth." },
  { slug: "mullingar", name: "Mullingar", county: "Westmeath", intro: "Mullingar businesses deserve access to top-tier marketing expertise. As the capital of Westmeath, Mullingar's growing business community benefits from our data-driven digital marketing strategies.", localDesc: "Whether you're a retailer on Dominick Street or a professional services firm in the town, we tailor our marketing approach to the unique needs of the Mullingar and Westmeath market." },
  { slug: "drogheda", name: "Drogheda", county: "Louth", intro: "As the largest town in Louth, Drogheda has a vibrant business community that increasingly relies on digital marketing to reach customers. We help Drogheda businesses maximise their online visibility and ROI.", localDesc: "From West Street to the Scotch Hall area, we understand Drogheda's local market and help businesses capture both local searches and wider regional demand." },
  { slug: "tallaght", name: "Tallaght", county: "Dublin", intro: "Tallaght is one of Dublin's most dynamic suburban centres, home to thousands of businesses competing for attention. Our marketing services help Tallaght businesses stand out in a crowded market.", localDesc: "Whether you operate near The Square, in Cookstown Industrial Estate, or anywhere in South Dublin, we deliver targeted digital marketing that connects you with local customers." },
  { slug: "blackrock", name: "Blackrock", county: "Dublin", intro: "Blackrock is a prestigious South Dublin suburb with a thriving commercial district. We help Blackrock businesses leverage digital marketing to reach their affluent local audience and beyond.", localDesc: "From the Blackrock Shopping Centre area to Frascati Road, we understand the high expectations of South Dublin consumers and craft marketing strategies that resonate." },
  { slug: "greystones", name: "Greystones", county: "Wicklow", intro: "Greystones has transformed into one of Ireland's most desirable towns, with a growing business community to match. We bring expert digital marketing services to Greystones and North Wicklow businesses.", localDesc: "Whether you're based in the town centre, Greystones Business Park, or the harbour area, our marketing strategies help you capture the growing local market and commuter audience." },
  { slug: "ashbourne", name: "Ashbourne", county: "Meath", intro: "Ashbourne's rapid growth has created a competitive business environment where effective digital marketing is essential. We help Ashbourne businesses compete with strategic, results-driven marketing.", localDesc: "From Ashbourne Retail Park to the town centre, we understand the demographics and buying patterns of this fast-growing Meath commuter town." },
  { slug: "swords", name: "Swords", county: "Dublin", intro: "As the county town of Fingal, Swords is a major commercial centre in North Dublin. Our marketing services help Swords businesses maximise their online presence and attract more customers.", localDesc: "Whether you're near Pavilions Shopping Centre, in Airside Business Park, or on Main Street, we deliver digital marketing that drives real results for North Dublin businesses." },
  { slug: "malahide", name: "Malahide", county: "Dublin", intro: "Malahide is one of Dublin's most affluent coastal suburbs, with businesses that demand premium marketing services. We deliver sophisticated digital strategies for Malahide's discerning business community.", localDesc: "From the village centre to the marina area, we help Malahide businesses reach their high-value target audience through strategic digital marketing." },
  { slug: "lucan", name: "Lucan", county: "Dublin", intro: "Lucan is a thriving West Dublin suburb with a growing population and business community. We provide expert marketing services that help Lucan businesses stand out online and attract local customers.", localDesc: "Whether you're based on the Main Street, in the village centre, or in surrounding business parks, we tailor our digital marketing to reach Lucan's active consumer base." },
  { slug: "blanchardstown", name: "Blanchardstown", county: "Dublin", intro: "Blanchardstown is Dublin's largest suburb and a major commercial hub. With intense competition, businesses here need expert digital marketing to capture their share of the West Dublin market.", localDesc: "From Blanchardstown Shopping Centre to the business parks along the N3 corridor, we help businesses in Dublin 15 maximise their online visibility and customer acquisition." },
  { slug: "bray", name: "Bray", county: "Wicklow", intro: "Bray is Wicklow's largest town and a popular destination for businesses and tourists alike. Our marketing services help Bray businesses capitalise on both local demand and visitor traffic.", localDesc: "Whether you're on the seafront, in the town centre, or in Bray Business Park, we deliver digital marketing strategies that drive footfall and online enquiries." },
  { slug: "maynooth", name: "Maynooth", county: "Kildare", intro: "Home to Ireland's second-oldest university, Maynooth has a unique market that blends academic, residential, and commercial audiences. We help Maynooth businesses reach all of these segments effectively.", localDesc: "From the Main Street to the Maynooth Business Campus, we understand the diverse demographics of this university town and craft marketing that resonates." },
  { slug: "leixlip", name: "Leixlip", county: "Kildare", intro: "Leixlip sits at the gateway between Dublin and Kildare, with a business community that benefits from this strategic location. We help Leixlip businesses maximise their digital presence.", localDesc: "Whether you're in the village centre, near the Hewlett-Packard campus, or along the M4 corridor, our marketing strategies put your business in front of the right audience." },
  { slug: "sandyford", name: "Sandyford", county: "Dublin", intro: "Sandyford Business District is one of Ireland's premier commercial centres. We provide sophisticated marketing services for the technology companies, professional services firms, and businesses in the Sandyford area.", localDesc: "From Sandyford Business Park to the surrounding areas of Leopardstown and Stillorgan, we deliver enterprise-level digital marketing that drives B2B and B2C growth." },
];

export function getArea(slug: string): AreaData | undefined {
  return areas.find((a) => a.slug === slug);
}
